<script src="<?= $_SESSION['R'].VENDORS.DS ?>jquery/jquery.min.js"></script>
<script src="<?= $_SESSION['R'].VENDORS.DS ?>codemirror/lib/codemirror.js"></script>
<script src="<?= $_SESSION['R'].VENDORS.DS ?>codemirror/mode/htmlmixed/htmlmixed.js"></script>
<script src="<?= $_SESSION['R'].VENDORS.DS ?>codemirror/mode/javascript/javascript.js"></script>
<script src="<?= $_SESSION['R'].VENDORS.DS ?>codemirror/mode/css/css.js"></script>
<script src="<?= $_SESSION['R'].VENDORS.DS ?>codemirror/mode/php/php.js"></script>
<script src="<?= $_SESSION['R'].VENDORS.DS ?>codemirror/mode/sql/sql.js"></script>   
<script src="<?= $_SESSION['R'].VENDORS.DS ?>codemirror/addon/edit/matchbrackets.js"></script>
<script src="<?= $_SESSION['R'].VENDORS.DS ?>codemirror/addon/display/fullscreen.js"></script>
<script src="<?= $_SESSION['R'].ASSETS.DS ?>js/lpb.js"></script>
